cmake_minimum_required(VERSION 3.12...3.21 FATAL_ERROR)

project(slxio)

set(slxio_cmake_dir "${PROJECT_SOURCE_DIR}/CMake")
list(INSERT CMAKE_MODULE_PATH 0 "${slxio_cmake_dir}")
include(CI)

if(APPLE)
  include(Apple)
endif()

if(WIN32)
  include(Windows)
endif()

set(SLXIO_SIMULINK_VERSION "R2018b")
set(SLXIO_64BIT_IDS  1)

option(SLXIO_BUILD_SHARED "Build as shared library" OFF)
option(SLXIO_BUILD_TESTS "Build library tests" ON)
option(SLXIO_COVERAGE "Enable code coverage" OFF)
option(SLXIO_LOGURU "Use Loguru librray for logging" FALSE)
option(SLXIO_SLOG  "Use slog librray for logging" TRUE)
option(SLXIO_ASAN "Enable AddressSanitizer (ASan)" OFF)
option(SLXIO_MSAN "Enable MemorySanitizer (MSan)" OFF)
option(SLXIO_TSAN "Enable ThreadSanitizer (TSan)" OFF)
option(SLXIO_UBSAN "Enable UndefinedBehaviorSanitizer (UBSan)" OFF)
option(SLXIO_OPENMP "Enable OpenMP support" ON)
option(SLXIO_PKGCONFIG  "Generate pkg-config file during build" ON)
option(SLXIO_INSTALL "Enable installtion after build" OFF)
option(SLXIO_DOCUMENTATION "Enable documentation generation" OFF)
option(SLXIO_BUILD_EXAMPLES "Build example applications" OFF)
option(SLXIO_BUILD_PYTHON "Enable building Python Interface" ON)
option(SLXIO_BUILD_LUA "Enable building Lua Interface" ON)
option(SLXIO_BUILD_JAVA "Enable building Java Interface" ON)
option(SLXIO_BUILD_PYTHON_TESTS "Build binding interface tests" ON)
option(SLXIO_FORCE_LOCAL_MODULES "Enable Using local installed modules" ON)
option(SLXIO_ENABLE_WERROR "Enable treating warnings as errors" OFF)
option(SLXIO_ENABLE_WALL "Enable all compiler warnings" ON)
option(SLXIO_MODULE_DEBUG "Enable Debugging module during build" OFF)
option(SLXIO_ENABLE_CPPCHECK "Enable cppcheck static analysis" OFF)
option(SLXIO_ENABLE_CLANG_TIDY "Enable clang-tidy static analysis" OFF)

include(CompilerChecks)
include(PlatformChecks)
include(CompilerPlatformFlags)
include(CompilerFlags)
include(CompilerExtraFlags)
include(CompilerWarningFlags)
include(Module)
include(ModuleThirdParty)
include(ModuleDebugging)
include(Sanitizer)
include(Version)
include(Testing)
include(Install)

add_submodules(${CMAKE_CURRENT_SOURCE_DIR})
summary()

