# SPDX-FileCopyrightText: 2025-2026 Wissem Chiha
# SPDX-License-Identifier: Apache-2.0

sonar.projectKey=wissem01chiha_slxio
sonar.organization=wissem01chiha
sonar.projectName=slxio
sonar.projectVersion=0.1.0
sonar.sources= Common, Simulink, IO
#sonar.sourceEncoding=UTF-8
