file (GLOB SLXIO_TEST_SOURCES src/*.cpp)
foreach (TEST_SOURCE_FILE IN LISTS SLXIO_TEST_SOURCES)
  get_filename_component (TEST_EXECUTABLE_NAME ${TEST_SOURCE_FILE} NAME_WE)
  add_executable (${TEST_EXECUTABLE_NAME} ${TEST_SOURCE_FILE})
  target_include_directories (${TEST_EXECUTABLE_NAME}
                              PRIVATE ${SLXIO_INCLUDE_DIRECTORIES})
  target_link_libraries (${TEST_EXECUTABLE_NAME} PRIVATE ${SLXIO_LINK_LIBRARIES} slxio)
  if (CMAKE_BUILD_TYPE STREQUAL "Debug")
    if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
      target_compile_options (${TEST_EXECUTABLE_NAME} PRIVATE -g -DDEBUG)
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
      target_compile_options (${TEST_EXECUTABLE_NAME} PRIVATE /Zi /DDEBUG)
      target_link_options (${TEST_EXECUTABLE_NAME} PRIVATE /DEBUG)
    endif ()
  endif ()
  add_dependencies (${TEST_EXECUTABLE_NAME} slxio)
  include (GoogleTest)
  gtest_discover_tests (${TEST_EXECUTABLE_NAME} WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
endforeach ()
