// SPDX-FileCopyrightText: 2025-2026 Wissem Chiha
// SPDX-License-Identifier: Apache-2.0

#ifndef SIMULINKBLOCKTYPE_H
#define SIMULINKBLOCKTYPE_H

#include "ABINamespaceMacro.h"
#include "APIExportMacro.h"
#include "PlatformTypes.h"
#include "SimulinkPCH.h"

namespace slxio
{
SLXIO_ABI_NAMESPACE_BEGIN

/**
 * @brief Enumeration of Simulink block types.
 */
enum class SimulinkBlockType
{

    BusCreator = 0,
    BusSelector,
    Constant,
    Delay,
    Demux,
    DiscreteTimeIntegrator,
    Gain,
    Ground,
    In1,
    Integrator,
    LogicalOperator,
    Mux,
    Out1,
    Product,
    RelationalOperator,
    Saturation,
    Scope,
    Subsystem,
    Sum,
    Switch,
    Terminator,
    VectorConcatenate,
    Derivative,
    IntegratorLimited,
    IntegratorSecondOrder,
    PidController,
    StateSpace,
    TransferFcn,
    TransportDelay,
    ZeroPole,
    Backlash,
    CoulombViscousFriction,
    DeadZone,
    HitCrossing,
    Pwm,
    Quantizer,
    Relay,
    SaturationDynamic,
    VariablePulseGenerator,
    WrapToZero,
    DiscreteDerivative,
    DiscreteFilter,
    DiscreteFIRFilter,
    DiscretePIDController,
    DiscreteStateSpace,
    DiscreteTransferFcn,
    DiscreteZeroPole,
    EnabledDelay,
    Memory,
    UnitDelay,
    ZeroOrderHold,
    BitClear,
    BitSet,
    BitToIntegerConverter,
    BitwiseOperator,
    CombinatorialLogic,
    CompareToConstant,
    CompareToZero,
    DetectChange,
    DetectIncrease,
    ExtractBits,
    IntegerToBitConverter,
    LogicalOperatorLogic,
    RelationalOperatorLogic,
    ShiftArithmetic,
    Cosine,
    D1DLookupTable,
    D2DLookupTable,
    DirectLookupTableND,
    InterpolationUsingPrelookup,
    LookupTableDynamic,
    NDLookupTable,
    Prelookup,
    Sine,
    Abs,
    Add,
    AlgebraicConstraint,
    Bias,
    ComplexToMagnitudeAngle,
    Divide,
    DotProduct,
    GainMath,
    Polynomial,
    ProductOfElements,
    ReciprocalSqrt,
    Reshape,
    RoundingFunction,
    Sign,
    Sqrt,
    Subtract,
    SumOfElements,
    TrigonometricFunction,
    UnaryMinus,
    WeightedSampleTimeMath,
    CreateDiagonalMatrix,
    CrossProduct,
    ExpandScalar,
    ExtractDiagonal,
    HermitianTranspose,
    IdentityMatrix,
    IsHermitian,
    IsSymmetric,
    IsTriangular,
    MatrixMultiply,
    MatrixSquare,
    PermuteMatrix,
    PixelProcessingSubsystem,
    Submatrix,
    Transpose,
    HitCrossingProbe,
    HitScheduler,
    MessageMerge,
    MessagePollingSubsystem,
    MessageTriggeredSubsystem,
    Queue,
    Receive,
    Send,
    SequenceViewer,
    Assertion,
    CheckDiscreteGradient,
    CheckDynamicGap,
    CheckDynamicLowerBound,
    CheckDynamicRange,
    CheckDynamicUpperBound,
    CheckInputResolution,
    CheckStaticGap,
    CheckStaticLowerBound,
    CheckStaticRange,
    CheckStaticUpperBound,
    BlockSupportTable,
    Docblock,
    ModelInfo,
    TimedBasedLinearization,
    TriggerBasedLinearization,
    AtomicSubsystem,
    CodereuseSubsystem,
    Enable,
    EnabledAndTriggeredSubsystem,
    EnabledSubsystem,
    ForEachSubsystem,
    ForIteratorSubsystem,
    FunctionCallFeedbackLatch,
    FunctionCallGenerator,
    FunctionCallSplit,
    FunctionCallSubsystem,
    FunctionElement,
    FunctionElementCall,
    If,
    IfActionSubsystem,
    In1Ports,
    InBusElement,
    Model,
    Out1Ports,
    OutBusElement,
    ResettableSubsystem,
    SubsystemPorts,
    SubsystemExamples,
    SubsystemReference,
    SwitchCase,
    SwitchCaseActionSubsystem,
    Trigger,
    TriggeredSubsystem,
    UnitSystemConfiguration,
    VariantAssemblySubsystem,
    VariantModel,
    VariantSubsystem,
    WhileIteratorSubsystem,
    Accumulator,
    Acos,
    Acosh,
    AddConstant,
    And,
    Asin,
    Asinh,
    Atan,
    Atan2,
    Atan2Cordic,
    Atanh,
    BitwiseAnd,
    BitwiseNand,
    BitwiseNor,
    BitwiseNot,
    BitwiseOr,
    BitwiseXor,
    Cast,
    CastToBoolean,
    CastToDouble,
    CastToSingle,
    CCCodeBlock

};

SLXIO_APIEXPORT std::string ToString(SimulinkBlockType type);

SLXIO_ABI_NAMESPACE_END
} // namespace slxio

#endif // SIMULINKBLOCKTYPE_H