// SPDX-FileCopyrightText: 2025-2026 Wissem Chiha
// SPDX-License-Identifier: Apache-2.0

#ifndef CORERCH_H
#define CORERCH_H

#include "ResultMap.h"

#define E_OK SLXIO_SRESULT(SLXIO_PROJECT, GLOBAL, GLOBAL, SLXIO_SUCCESS, 0U)

#define E_INVALID_FUNCTION SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 1U)
#define E_FILE_NOT_FOUND SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 2U)
#define E_PATH_NOT_FOUND SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 3U)
#define E_PATH_TOO_LONG SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 4U)
#define E_MESSAGE_TOO_LARGE SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 5U)
#define E_PATH_EMPTY SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 6U)
#define E_TOO_MANY_OPEN_FILES SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 7U)
#define E_FILE_OPEN_FAIL SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 8U)
#define E_INVALID_HANDLE SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 9U)
#define E_INVALID_FILE_MODE SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 10U)
#define E_STREAM_WRITE_FAIL SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 11U)
#define E_STREAM_EMPTY_OUTPUT SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 12U)
#define E_NOT_IMPLEMENTED SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 13U)
#define E_INVALID_ARGUMENT SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 14U)
#define E_PARAMETER_NULL_PTR SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 15U)
#define E_INVALID_DATA_TYPE SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 16U)
#define E_DIRECTORY_NOT_EXIST SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 17U)
#define E_FILE_REMOVE_FAILED SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 18U)

#define E_CONFIG_ALREADY_ACTIVE SLXIO_SRESULT(SLXIO_PROJECT, COMMON, CORE, SLXIO_FATAL, 27U)

#endif // CORERCH_H