// SPDX-FileCopyrightText: 2025-2026 Wissem Chiha
// SPDX-License-Identifier: Apache-2.0

#ifndef DATATYPE_H
#define DATATYPE_H

#include "ABINamespaceMacro.h"
#include "PlatformTypes.h"

namespace slxio
{
SLXIO_ABI_NAMESPACE_BEGIN

/**
 * @enum DataType
 * @brief Values Returned by GetDataType 
 */
enum class DataType : UInt16 {

    SLXIO_TYPE_UNKNOWN = 0,
    SLXIO_TYPE_BOOL,
    SLXIO_TYPE_CHAR,
    SLXIO_TYPE_INTEGER,
    SLXIO_TYPE_FLOAT,
    SLXIO_TYPE_STRING,
    SLXIO_TYPE_ARRAY,
    SLXIO_TYPE_VECTOR,
    SLXIO_TYPE_MAP,
    SLXIO_TYPE_XML_DOCUMENT,
    SLXIO_TYPE_XML_NODE,
    SLXIO_TYPE_XML_CHAR,
    SLXIO_TYPE_XML_FILE,
    SLXIO_TYPE_POINTER,
    SLXIO_TYPE_JSON_OBJECT,
    SLXIO_TYPE_NULL_POINTER,
    SLXIO_TYPE_ZIP_ARCHIVE,
    SLXIO_TYPE_ZIP_ENTRY,
    SLXIO_TYPE_ZIP_FILE,
    SLXIO_TYPE_ARCHIVE,
    SLXIO_TYPE_DIRECTORY,
    SLXIO_TYPE_FILE,
    SLXIO_TYPE_ASYNCHRONOUS_LOGGER,
    SLXIO_TYPE_SYNCHRONOUS_LOGGER,
    SLXIO_TYPE_SIMULINK_ARRAY,
    SLXIO_TYPE_SIMULINK_OBJECT,
    SLXIO_TYPE_SIMULINK_ELEMENT,
    SLXIO_TYPE_SIMULINK_MODEL,
    SLXIO_TYPE_SIMULINK_ROOT,
    SLXIO_TYPE_SIMULINK_BLOCK,
    SLXIO_TYPE_SIMULINK_ATOMIC_SUBSYSTEM,
    SLXIO_TYPE_SIMULINK_ENABLED_SUBSYSTEM,
    SLXIO_TYPE_SIMULINK_TRIGGERED_SUBSYSTEM,
    SLXIO_TYPE_SIMULINK_SUBSYSTEM,
    SLXIO_TYPE_SIMULINK_PORT,
    SLXIO_TYPE_SIMULINK_LINE,
    SLXIO_TYPE_SIMULINK_SIGNAL,
    SLXIO_TYPE_SIMULINK_PARAMETER,
    SLXIO_TYPE_SIMULINK_CONFIG_SET,
    SLXIO_TYPE_SIMULINK_DEBUGGING,
    SLXIO_TYPE_SIMULINK_HARDWARE,
    SLXIO_TYPE_SIMULINK_MODEL_REFERENCE,
    SLXIO_TYPE_SIMULINK_OPTIMIZATION,
    SLXIO_TYPE_SIMULINK_RTW,
    SLXIO_TYPE_SIMULINK_SFSIM,
    SLXIO_TYPE_SIMULINK_SOLVER,
    SLXIO_TYPE_COLOR,
    SLXIO_TYPE_SIMULINK_COLOR,
    SLXIO_TYPE_1D_LOOKUP_TABLE,
    SLXIO_TYPE_2D_LOOKUP_TABLE,
    SLXIO_TYPE_ND_LOOKUP_TABLE,
    SLXIO_TYPE_ABS,
    SLXIO_TYPE_ADD,
    SLXIO_TYPE_ALGEBRAIC_CONSTRAINT,
    SLXIO_TYPE_BIT_CLEAR,
    SLXIO_TYPE_BIT_SET,
    SLXIO_TYPE_CONSTANT,
    SLXIO_TYPE_DATA_STORE_MEMORY,
    SLXIO_TYPE_DATA_STORE_READ,
    SLXIO_TYPE_DATA_STORE_WRITE,
    SLXIO_TYPE_DATA_TYPE_CONVERSION,
    SLXIO_TYPE_DELAY,
    SLXIO_TYPE_DERIVATIVE,
    SLXIO_TYPE_DISCRETE_DERIVATIVE,
    SLXIO_TYPE_DISCRETE_FILTER,
    SLXIO_TYPE_GAIN,
    SLXIO_TYPE_GROUND,
    SLXIO_TYPE_INTEGRATOR,
    SLXIO_TYPE_INTEGRATOR_LIMITED,
    SLXIO_TYPE_INTEGRATOR_SECOND_ORDER,
    SLXIO_TYPE_LOGICAL_OPERATOR,
    SLXIO_TYPE_MUX,
    SLXIO_TYPE_PRODUCT,
    SLXIO_TYPE_RELATIONAL_OPERATOR,
    SLXIO_TYPE_SATURATION,
    SLXIO_TYPE_SCOPE,
    SLXIO_TYPE_STATE_SPACE,
    SLXIO_TYPE_SUBSYSTEM,
    SLXIO_TYPE_SUM,
    SLXIO_TYPE_SWITCH,
    SLXIO_TYPE_TERMINATOR,
    SLXIO_TYPE_TRANSFER_FCN,
    SLXIO_TYPE_CODER_INFO,
    SLXIO_TYPE_EDITOR_SETTINGS,
    SLXIO_TYPE_SIMULATION_SETTINGS,
    SLXIO_TYPE_STATEFLOW_BLOCK,
    SLXIO_TYPE_STATEFLOW_CHART,
    SLXIO_TYPE_STATEFLOW_DATA,
    SLXIO_TYPE_STATEFLOW_EVENT,
    SLXIO_TYPE_STATEFLOW_JUNCTION,
    SLXIO_TYPE_STATEFLOW_MACHINE,
    SLXIO_TYPE_STATEFLOW_STATE,
    SLXIO_TYPE_STATEFLOW_TARGET,
    SLXIO_TYPE_STATEFLOW_TRANSITION
};

SLXIO_ABI_NAMESPACE_END
};


#endif // DATATYPE_H