// SPDX-FileCopyrightText: 2025-2026 Wissem Chiha
// SPDX-License-Identifier: Apache-2.0

#ifndef DATATYPE_H
#define DATATYPE_H

#include "ABINamespaceMacro.h"
#include "PlatformTypes.h"

namespace slxio
{
SLXIO_ABI_NAMESPACE_BEGIN

/**
 * @enum DataType
 * @brief Values Returned by GetDataType
 */
enum class DataType : UInt16
{
    SLXIO_TYPE_NONE = 0,
    SLXIO_TYPE_BOOL,
    SLXIO_TYPE_CHAR,
    SLXIO_TYPE_INTEGER,
    SLXIO_TYPE_FLOAT,
    SLXIO_TYPE_STRING,
    SLXIO_TYPE_ARRAY,
    SLXIO_TYPE_VECTOR,
    SLXIO_TYPE_LIST,
    SLXIO_TYPE_MAP,
    SLXIO_TYPE_BIT,
    SLXIO_TYPE_ERROR_LOG_MESSAGE,
    SLXIO_TYPE_ARRAYLOGMESSAGE,
    SLXIO_TYPE_GENERIC_LOGGER,
    SLXIO_TYPE_CJSON_OBJECT,
    SLXIO_TYPE_LIBXML_DOCPTR,
    SLXIO_TYPE_GENERIC_PARAMETER_DATA_OBJECT,
    SLXIO_TYPE_MODELWORKSPACE_PARAMETER,
    SLXIO_TYPE_LIBXML_XMLCHAR,
    SLXIO_TYPE_LIBXML_XML_NODE,
    SLXIO_TYPE_SIMULINK_PARAM
};

SLXIO_ABI_NAMESPACE_END
}; // namespace slxio

#endif // DATATYPE_H