// SPDX-FileCopyrightText: 2025-2026 Wissem Chiha
// SPDX-License-Identifier: Apache-2.0

#ifndef DATATYPE_H
#define DATATYPE_H

#include "ABINamespaceMacro.h"
#include "PlatformTypes.h"

namespace slxio
{
SLXIO_ABI_NAMESPACE_BEGIN

/**
 * @enum DataType
 * @brief Values Returned by GetDataType
 */
enum class DataType : UInt16
{
  SLXIO_TYPE_NONE = 0,
  SLXIO_TYPE_BOOL,
  SLXIO_TYPE_CHAR,
  SLXIO_TYPE_INTEGER,
  SLXIO_TYPE_FLOAT,
  SLXIO_TYPE_STRING,
  SLXIO_TYPE_ARRAY,
  SLXIO_TYPE_VECTOR,
  SLXIO_TYPE_MAP,
  SLXIO_TYPE_POINTER,
  SLXIO_TYPE_COLOR,
  SLXIO_TYPE_BIT,
  SLXIO_TYPE_GENERIC_LOGGER,
  SLXIO_TYPE_GENERIC_LOGMESSAGE,
  SLXIO_TYPE_DATA_OBJECT,
  SLXIO_TYPE_SIMULINK_MODEL,
  SLXIO_TYPE_SIMULINK_SUBSYSTEM,
  SLXIO_TYPE_SIMULINK_BLOCK,
  SLXIO_TYPE_SIMULINK_SIGNAL,
  SLXIO_TYPE_SIMULINK_PARAMETER,
  SLXIO_TYPE_SIMULINK_CONFIGURATION,
  SLXIO_TYPE_SIMULINK_PORT,
  SLXIO_TYPE_SIMULINK_LINE
};

SLXIO_ABI_NAMESPACE_END
};

#endif // DATATYPE_H