// SPDX-FileCopyrightText: 2025-2026 Wissem Chiha
// SPDX-License-Identifier: Apache-2.0

//===============================================================
// AUTOGENERATED BY MergeEnumMap.py SCRIPT — DO NOT EDIT BY HAND!
//===============================================================

#ifndef __ErrorTypes_h__
#define __ErrorTypes_h__


#ifdef SLX_OK
#undef SLX_OK
#endif
#define SLX_OK  0x0A0A0000

#ifdef SLX_ENOENT
#undef SLX_ENOENT
#endif
#define SLX_ENOENT  0x0A0A0001

#ifdef SLX_EINVAR
#undef SLX_EINVAR
#endif
#define SLX_EINVAR  0x0A0A0002

#ifdef SLX_ETYPEMISMATCH
#undef SLX_ETYPEMISMATCH
#endif
#define SLX_ETYPEMISMATCH  0x0A0A0003

#ifdef SLX_ENULLPTR
#undef SLX_ENULLPTR
#endif
#define SLX_ENULLPTR  0x0A0A0004

#ifdef SLX_ENOTIMPL
#undef SLX_ENOTIMPL
#endif
#define SLX_ENOTIMPL  0x0A0A0005

#ifdef SLX_EEXTNSUP
#undef SLX_EEXTNSUP
#endif
#define SLX_EEXTNSUP  0x0A0A0006

#ifdef SLX_EINVALIDX
#undef SLX_EINVALIDX
#endif
#define SLX_EINVALIDX  0x0A0A0008

#ifdef SLX_EDUPOBJ
#undef SLX_EDUPOBJ
#endif
#define SLX_EDUPOBJ  0x0A0A0009

#ifdef SLX_EIOERR
#undef SLX_EIOERR
#endif
#define SLX_EIOERR  0x0A0A000A

#ifdef SLX_EEOF
#undef SLX_EEOF
#endif
#define SLX_EEOF  0x0A0A000B

#ifdef SLX_EGETCWD
#undef SLX_EGETCWD
#endif
#define SLX_EGETCWD  0x0A0A000C

#ifdef SLX_ELONGPATH
#undef SLX_ELONGPATH
#endif
#define SLX_ELONGPATH  0x0A0A000D

#ifdef SLX_ECASTFAIL
#undef SLX_ECASTFAIL
#endif
#define SLX_ECASTFAIL  0x0A0A000E

#ifdef SLX_EMEMALLOC
#undef SLX_EMEMALLOC
#endif
#define SLX_EMEMALLOC  0x0A0A000F

#ifdef SLX_ENOTCONN
#undef SLX_ENOTCONN
#endif
#define SLX_ENOTCONN  0x0A0A0010

#ifdef SLX_ECYCLE
#undef SLX_ECYCLE
#endif
#define SLX_ECYCLE  0x0A0A0011

#ifdef SLX_EUNSUPPORTED
#undef SLX_EUNSUPPORTED
#endif
#define SLX_EUNSUPPORTED  0x0A0A0012

#ifdef SLX_ELOCKED
#undef SLX_ELOCKED
#endif
#define SLX_ELOCKED  0x0A0A0013

#ifdef SLX_ESTATEINVAL
#undef SLX_ESTATEINVAL
#endif
#define SLX_ESTATEINVAL  0x0A0A0014

#ifdef SLX_EPARAMINVAL
#undef SLX_EPARAMINVAL
#endif
#define SLX_EPARAMINVAL  0x0A0A0015

#ifdef SLX_EBLOCKNF
#undef SLX_EBLOCKNF
#endif
#define SLX_EBLOCKNF  0x0A0A0016

#ifdef SLX_EPORTNF
#undef SLX_EPORTNF
#endif
#define SLX_EPORTNF  0x0A0A0017

#ifdef SLX_ELINKFAIL
#undef SLX_ELINKFAIL
#endif
#define SLX_ELINKFAIL  0x0A0A0018

#ifdef SLX_EUNRESOLVED
#undef SLX_EUNRESOLVED
#endif
#define SLX_EUNRESOLVED  0x0A0A0019

#ifdef SLX_EUNKNOWN
#undef SLX_EUNKNOWN
#endif
#define SLX_EUNKNOWN  0x0A0A001A

#ifdef CONFIG_ACTIVE
#undef CONFIG_ACTIVE
#endif
#define CONFIG_ACTIVE  0x0E110001

#ifdef UV__EOF
#undef UV__EOF
#endif
#define UV__EOF  0x101E0FFF

#ifdef UV__UNKNOWN
#undef UV__UNKNOWN
#endif
#define UV__UNKNOWN  0x101E0FFE

#ifdef UV__EAI_ADDRFAMILY
#undef UV__EAI_ADDRFAMILY
#endif
#define UV__EAI_ADDRFAMILY  0x101E0BB8

#ifdef UV__EAI_AGAIN
#undef UV__EAI_AGAIN
#endif
#define UV__EAI_AGAIN  0x101E0BB9

#ifdef UV__EAI_BADFLAGS
#undef UV__EAI_BADFLAGS
#endif
#define UV__EAI_BADFLAGS  0x101E0BBA

#ifdef UV__EAI_CANCELED
#undef UV__EAI_CANCELED
#endif
#define UV__EAI_CANCELED  0x101E0BBB

#ifdef UV__EAI_FAIL
#undef UV__EAI_FAIL
#endif
#define UV__EAI_FAIL  0x101E0BBC

#ifdef UV__EAI_FAMILY
#undef UV__EAI_FAMILY
#endif
#define UV__EAI_FAMILY  0x101E0BBD

#ifdef UV__EAI_MEMORY
#undef UV__EAI_MEMORY
#endif
#define UV__EAI_MEMORY  0x101E0BBE

#ifdef UV__EAI_NODATA
#undef UV__EAI_NODATA
#endif
#define UV__EAI_NODATA  0x101E0BBF

#ifdef UV__EAI_NONAME
#undef UV__EAI_NONAME
#endif
#define UV__EAI_NONAME  0x101E0BC0

#ifdef UV__EAI_OVERFLOW
#undef UV__EAI_OVERFLOW
#endif
#define UV__EAI_OVERFLOW  0x101E0BC1

#ifdef UV__EAI_SERVICE
#undef UV__EAI_SERVICE
#endif
#define UV__EAI_SERVICE  0x101E0BC2

#ifdef UV__EAI_SOCKTYPE
#undef UV__EAI_SOCKTYPE
#endif
#define UV__EAI_SOCKTYPE  0x101E0BC3

#ifdef UV__EAI_BADHINTS
#undef UV__EAI_BADHINTS
#endif
#define UV__EAI_BADHINTS  0x101E0BC5

#ifdef UV__EAI_PROTOCOL
#undef UV__EAI_PROTOCOL
#endif
#define UV__EAI_PROTOCOL  0x101E0BC6

#ifdef UV__E2BIG
#undef UV__E2BIG
#endif
#define UV__E2BIG  0x101E0FFD

#ifdef UV__EACCES
#undef UV__EACCES
#endif
#define UV__EACCES  0x101E0FFC

#ifdef UV__EADDRINUSE
#undef UV__EADDRINUSE
#endif
#define UV__EADDRINUSE  0x101E0FFB

#ifdef UV__EADDRNOTAVAIL
#undef UV__EADDRNOTAVAIL
#endif
#define UV__EADDRNOTAVAIL  0x101E0FFA

#ifdef UV__EAFNOSUPPORT
#undef UV__EAFNOSUPPORT
#endif
#define UV__EAFNOSUPPORT  0x101E0FF9

#ifdef UV__EAGAIN
#undef UV__EAGAIN
#endif
#define UV__EAGAIN  0x101E0FF8

#ifdef UV__EALREADY
#undef UV__EALREADY
#endif
#define UV__EALREADY  0x101E0FF4

#ifdef UV__EBADF
#undef UV__EBADF
#endif
#define UV__EBADF  0x101E0FF3

#ifdef UV__EBUSY
#undef UV__EBUSY
#endif
#define UV__EBUSY  0x101E0FF2

#ifdef UV__ECANCELED
#undef UV__ECANCELED
#endif
#define UV__ECANCELED  0x101E0FF1

#ifdef UV__ECHARSET
#undef UV__ECHARSET
#endif
#define UV__ECHARSET  0x101E0FF0

#ifdef UV__ECONNABORTED
#undef UV__ECONNABORTED
#endif
#define UV__ECONNABORTED  0x101E0FEF

#ifdef UV__ECONNREFUSED
#undef UV__ECONNREFUSED
#endif
#define UV__ECONNREFUSED  0x101E0FEE

#ifdef UV__ECONNRESET
#undef UV__ECONNRESET
#endif
#define UV__ECONNRESET  0x101E0FED

#ifdef UV__EDESTADDRREQ
#undef UV__EDESTADDRREQ
#endif
#define UV__EDESTADDRREQ  0x101E0FEC

#ifdef UV__EEXIST
#undef UV__EEXIST
#endif
#define UV__EEXIST  0x101E0FEB

#ifdef UV__EFAULT
#undef UV__EFAULT
#endif
#define UV__EFAULT  0x101E0FEA

#ifdef UV__EHOSTUNREACH
#undef UV__EHOSTUNREACH
#endif
#define UV__EHOSTUNREACH  0x101E0FE9

#ifdef UV__EINTR
#undef UV__EINTR
#endif
#define UV__EINTR  0x101E0FE8

#ifdef UV__EINVAL
#undef UV__EINVAL
#endif
#define UV__EINVAL  0x101E0FE7

#ifdef UV__EIO
#undef UV__EIO
#endif
#define UV__EIO  0x101E0FE6

#ifdef UV__EISCONN
#undef UV__EISCONN
#endif
#define UV__EISCONN  0x101E0FE5

#ifdef UV__EISDIR
#undef UV__EISDIR
#endif
#define UV__EISDIR  0x101E0FE4

#ifdef UV__ELOOP
#undef UV__ELOOP
#endif
#define UV__ELOOP  0x101E0FE3

#ifdef UV__EMFILE
#undef UV__EMFILE
#endif
#define UV__EMFILE  0x101E0FE2

#ifdef UV__EMSGSIZE
#undef UV__EMSGSIZE
#endif
#define UV__EMSGSIZE  0x101E0FE1

#ifdef UV__ENAMETOOLONG
#undef UV__ENAMETOOLONG
#endif
#define UV__ENAMETOOLONG  0x101E0FE0

#ifdef UV__ENETDOWN
#undef UV__ENETDOWN
#endif
#define UV__ENETDOWN  0x101E0FDF

#ifdef UV__ENETUNREACH
#undef UV__ENETUNREACH
#endif
#define UV__ENETUNREACH  0x101E0FDE

#ifdef UV__ENFILE
#undef UV__ENFILE
#endif
#define UV__ENFILE  0x101E0FDD

#ifdef UV__ENOBUFS
#undef UV__ENOBUFS
#endif
#define UV__ENOBUFS  0x101E0FDC

#ifdef UV__ENODEV
#undef UV__ENODEV
#endif
#define UV__ENODEV  0x101E0FDB

#ifdef UV__ENOENT
#undef UV__ENOENT
#endif
#define UV__ENOENT  0x101E0FDA

#ifdef UV__ENOMEM
#undef UV__ENOMEM
#endif
#define UV__ENOMEM  0x101E0FD9

#ifdef UV__ENONET
#undef UV__ENONET
#endif
#define UV__ENONET  0x101E0FD8

#ifdef UV__ENOSPC
#undef UV__ENOSPC
#endif
#define UV__ENOSPC  0x101E0FD7

#ifdef UV__ENOSYS
#undef UV__ENOSYS
#endif
#define UV__ENOSYS  0x101E0FD6

#ifdef UV__ENOTCONN
#undef UV__ENOTCONN
#endif
#define UV__ENOTCONN  0x101E0FD5

#ifdef UV__ENOTDIR
#undef UV__ENOTDIR
#endif
#define UV__ENOTDIR  0x101E0FD4

#ifdef UV__ENOTEMPTY
#undef UV__ENOTEMPTY
#endif
#define UV__ENOTEMPTY  0x101E0FD3

#ifdef UV__ENOTSOCK
#undef UV__ENOTSOCK
#endif
#define UV__ENOTSOCK  0x101E0FD2

#ifdef UV__ENOTSUP
#undef UV__ENOTSUP
#endif
#define UV__ENOTSUP  0x101E0FD1

#ifdef UV__EPERM
#undef UV__EPERM
#endif
#define UV__EPERM  0x101E0FD0

#ifdef UV__EPIPE
#undef UV__EPIPE
#endif
#define UV__EPIPE  0x101E0FCF

#ifdef UV__EPROTO
#undef UV__EPROTO
#endif
#define UV__EPROTO  0x101E0FCE

#ifdef UV__EPROTONOSUPPORT
#undef UV__EPROTONOSUPPORT
#endif
#define UV__EPROTONOSUPPORT  0x101E0FCD

#ifdef UV__EPROTOTYPE
#undef UV__EPROTOTYPE
#endif
#define UV__EPROTOTYPE  0x101E0FCC

#ifdef UV__EROFS
#undef UV__EROFS
#endif
#define UV__EROFS  0x101E0FCB

#ifdef UV__ESHUTDOWN
#undef UV__ESHUTDOWN
#endif
#define UV__ESHUTDOWN  0x101E0FCA

#ifdef UV__ESPIPE
#undef UV__ESPIPE
#endif
#define UV__ESPIPE  0x101E0FC9

#ifdef UV__ESRCH
#undef UV__ESRCH
#endif
#define UV__ESRCH  0x101E0FC8

#ifdef UV__ETIMEDOUT
#undef UV__ETIMEDOUT
#endif
#define UV__ETIMEDOUT  0x101E0FC7

#ifdef UV__ETXTBSY
#undef UV__ETXTBSY
#endif
#define UV__ETXTBSY  0x101E0FC6

#ifdef UV__EXDEV
#undef UV__EXDEV
#endif
#define UV__EXDEV  0x101E0FC5

#ifdef UV__EFBIG
#undef UV__EFBIG
#endif
#define UV__EFBIG  0x101E0FC4

#ifdef UV__ENOPROTOOPT
#undef UV__ENOPROTOOPT
#endif
#define UV__ENOPROTOOPT  0x101E0FC3

#ifdef UV__ERANGE
#undef UV__ERANGE
#endif
#define UV__ERANGE  0x101E0FC2

#ifdef UV__ENXIO
#undef UV__ENXIO
#endif
#define UV__ENXIO  0x101E0FC1

#ifdef UV__EMLINK
#undef UV__EMLINK
#endif
#define UV__EMLINK  0x101E0FC0

#ifdef UV__EHOSTDOWN
#undef UV__EHOSTDOWN
#endif
#define UV__EHOSTDOWN  0x101E0FBF

#ifdef UV__EREMOTEIO
#undef UV__EREMOTEIO
#endif
#define UV__EREMOTEIO  0x101E0FBE

#ifdef UV__ENOTTY
#undef UV__ENOTTY
#endif
#define UV__ENOTTY  0x101E0FBD

#ifdef UV__EFTYPE
#undef UV__EFTYPE
#endif
#define UV__EFTYPE  0x101E0FBC

#ifdef UV__EILSEQ
#undef UV__EILSEQ
#endif
#define UV__EILSEQ  0x101E0FBB

#ifdef UV__EOVERFLOW
#undef UV__EOVERFLOW
#endif
#define UV__EOVERFLOW  0x101E0FBA

#ifdef UV__ESOCKTNOSUPPORT
#undef UV__ESOCKTNOSUPPORT
#endif
#define UV__ESOCKTNOSUPPORT  0x101E0FB9

#ifdef UV__ENODATA
#undef UV__ENODATA
#endif
#define UV__ENODATA  0x101E0FB8

#ifdef UV__EUNATCH
#undef UV__EUNATCH
#endif
#define UV__EUNATCH  0x101E0FB7

#ifdef UV__ENOEXEC
#undef UV__ENOEXEC
#endif
#define UV__ENOEXEC  0x101E0FB6

#endif /* __ErrorTypes_h__*/ 
