// Copyright 2025-2026 Wissem Chiha
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.

#include "ABINamespace.h"
#include "APIExport.h"
#include "SimulinkBlock.h"
#include "SimulinkElementType.h"
#include "Type.h"
#include <memory>

SLXIO_NAMESPACE_BEGIN
SLXIO_ABI_NAMESPACE_BEGIN

class StateflowChart;

/**
 * @brief A special Simulink block that stores state charts. There is
 * a one-to-one association between StateflowBlock and StateflowChart.
 * The sub blocks of this block are automatically generated by
 * Simulink.
 */
class APIEXPORT StateflowBlock : public SimulinkBlock
{
public:
  StateflowBlock() = default;
  StateflowBlock(StateflowChart& chart);
  StateflowBlock(StateflowBlock& block);

  /// @brief  Get a pointer to the StateflowChart which the blcok
  /// belong to
  std::shared_ptr<StateflowChart> getChart();

  /// @brief Remove this block from the StateflowChart
  ErrorCode remove();

private:
  std::shared_ptr<StateflowChart> chart;
};

SLXIO_ABI_NAMESPACE_END
SLXIO_NAMESPACE_END