// SPDX-FileCopyrightText: 2025-2026 Wissem Chiha
// SPDX-License-Identifier: Apache-2.0

#include "ABINamespaceMacro.h"
#include "APIExportMacro.h"
#include "PlatformTypes.h"
#include "SimulinkBlock.h"
#include "SimulinkElementType.h"

#include <memory>

namespace slxio {
SLXIO_ABI_NAMESPACE_BEGIN

class StateflowChart;

/**
 * @brief A special Simulink block that stores state charts. There is
 * a one-to-one association between StateflowBlock and StateflowChart.
 * The sub blocks of this block are automatically generated by
 * Simulink.
 */
class SLXIO_APIEXPORT StateflowBlock : public SimulinkBlock
{
public:
  StateflowBlock() = default;
  StateflowBlock(StateflowChart& chart);
  StateflowBlock(StateflowBlock& block);

  /// @brief  Get a pointer to the StateflowChart which the blcok
  /// belong to
  std::shared_ptr<StateflowChart> getChart();

  /// @brief Remove this block from the StateflowChart
  HError RemoveElement();

private:
  std::shared_ptr<StateflowChart> chart;
};

SLXIO_ABI_NAMESPACE_END
}; // namespace slxio
