include(CheckIncludeFile)
include(CheckIncludeFiles)
include(CheckTypeSize)

check_include_file("fcntl.h"  HAVE_FCNTL_H)
check_include_file("inttypes.h"  HAVE_INTTYPES_H)
check_include_file(limits.h HAVE_LIMITS_H)
check_include_files(stdbool.h HAVE_STDBOOL_H)
check_include_files(unistd.h  HAVE_UNISTD_H)
check_include_files(inttypes.h HAVE_INTTYPES_H_LIBZIP)
check_include_files(stdint.h  HAVE_STDINT_H_LIBZIP)
check_include_files(sys/types.h  HAVE_SYS_TYPES_H_LIBZIP)
check_include_files(stdint.h  HAVE_STDINT_H)
check_include_files(sys/types.h  HAVE_SYS_TYPES_H)
check_include_files(values.h  HAVE_VALUES_H)
check_include_files(stdlib.h  HAVE_STDLIB_H)
check_include_files(float.h HAVE_FLOAT_H)
check_include_files(direct.h  HAVE_DIRECT_H)
check_include_files(io.h HAVE_IO_H)
check_include_files(windows.h HAVE_WINDOWS_H)

check_type_size("char" SLXIO_ABI_SIZEOF_CHAR)
check_type_size(int SLXIO_ABI_SIZEOF_INT)
check_type_size("long" SLXIO_ABI_SIZEOF_LONG)
check_type_size("short"  SLXIO_ABI_SIZEOF_SHORT)
check_type_size("long long" SLXIO_ABI_SIZEOF_LONG_LONG)
check_type_size("size_t" SLXIO_ABI_SIZEOF_SIZE_T)
check_type_size("double" SLXIO_ABI_SIZEOF_DOUBLE)
check_type_size("float"  SLXIO_ABI_SIZEOF_FLOAT)
check_type_size(uint8_t  SLXIO_ABI_SIZEOF_UINT8_T)
check_type_size(uint16_t SLXIO_ABI_SIZEOF_UINT16_T)
check_type_size(uint32_t SLXIO_ABI_SIZEOF_UINT32_T)
