include(CheckIncludeFile)
include(CheckIncludeFiles)
include(CheckFunctionExists)
include(CheckSymbolExists)
include(CheckTypeSize)
include(CheckCSourceCompiles)


check_include_file("fcntl.h"        HAVE_FCNTL_H)
check_include_file("inttypes.h"     HAVE_INTTYPES_H)
check_include_file(stdarg.h         HAVE_STDARG_H)
check_include_file(strings.h        HAVE_STRINGS_H)
check_include_file(string.h         HAVE_STRING_H)
check_include_file(syslog.h         HAVE_SYSLOG_H)
check_include_file(limits.h         HAVE_LIMITS_H)
check_include_files(stdbool.h       HAVE_STDBOOL_H)
check_include_files(unistd.h        HAVE_UNISTD_H)
check_include_files(inttypes.h      HAVE_INTTYPES_H_LIBZIP)
check_include_files(stdint.h        HAVE_STDINT_H_LIBZIP)
check_include_files(sys/types.h     HAVE_SYS_TYPES_H_LIBZIP)
check_include_files(stdint.h        HAVE_STDINT_H)
check_include_files(sys/types.h     HAVE_SYS_TYPES_H)
check_include_files(values.h        HAVE_VALUES_H)
check_include_files(stdlib.h        HAVE_STDLIB_H)
check_include_files(float.h         HAVE_FLOAT_H)
check_include_files(direct.h        HAVE_DIRECT_H)
check_include_files(io.h            HAVE_IO_H)
check_include_files(windows.h       HAVE_WINDOWS_H)

check_function_exists(_close       HAVE__CLOSE)
check_function_exists(_fseeki64    HAVE__FSEEKI64)
check_function_exists(_fstat64     HAVE__FSTAT64)
check_function_exists(_ftelli64    HAVE__FTELLI64)
check_function_exists(_setmode     HAVE__SETMODE)
check_function_exists(_stat64      HAVE__STAT64)
check_function_exists(_strdup      HAVE__STRDUP)
check_function_exists(_strtoi64    HAVE__STRTOI64)
check_function_exists(_strtoui64   HAVE__STRTOUI64)
check_function_exists(_unlink      HAVE__UNLINK)
check_function_exists(arc4random   HAVE_ARC4RANDOM)
check_function_exists(clonefile    HAVE_CLONEFILE)
check_function_exists(explicit_bzero HAVE_EXPLICIT_BZERO)
check_function_exists(explicit_memset HAVE_EXPLICIT_MEMSET)
check_function_exists(fchmod HAVE_FCHMOD)
check_function_exists(fileno HAVE_FILENO)
check_function_exists(fseeko HAVE_FSEEKO)
check_function_exists(ftello HAVE_FTELLO)
check_function_exists(getprogname HAVE_GETPROGNAME)
check_function_exists(GetSecurityInfo HAVE_GETSECURITYINFO)
check_function_exists(memcpy_s HAVE_MEMCPY_S)
check_function_exists(random HAVE_RANDOM)
check_function_exists(setmode HAVE_SETMODE)
check_function_exists(strdup HAVE_STRDUP)
check_function_exists(strerror_s HAVE_STRERROR_S)
check_function_exists(strerrorlen_s HAVE_STRERRORLEN_S)
check_function_exists(stricmp HAVE_STRICMP)
check_function_exists(strncpy_s HAVE_STRNCPY_S)
check_function_exists(strtoll HAVE_STRTOLL)
check_function_exists(strtoull HAVE_STRTOULL)
check_function_exists(_dup HAVE__DUP)
check_function_exists(_fdopen HAVE__FDOPEN)
check_function_exists(_fileno HAVE__FILENO)
check_function_exists(_strtoi64 HAVE__STRTOI64)
check_function_exists(_strtoui64 HAVE__STRTOUI64)
check_function_exists(_unlink HAVE__UNLINK)
check_function_exists(arc4random HAVE_ARC4RANDOM)
check_function_exists(clonefile HAVE_CLONEFILE)
check_function_exists(explicit_bzero HAVE_EXPLICIT_BZERO)
check_function_exists(explicit_memset HAVE_EXPLICIT_MEMSET)
check_function_exists(fchmod HAVE_FCHMOD)
check_function_exists(fileno HAVE_FILENO)
check_function_exists(fseeko HAVE_FSEEKO)
check_function_exists(ftello HAVE_FTELLO)
check_function_exists(getprogname HAVE_GETPROGNAME)
check_function_exists(GetSecurityInfo HAVE_GETSECURITYINFO)
check_function_exists(memcpy_s HAVE_MEMCPY_S)
check_function_exists(random HAVE_RANDOM)
check_function_exists(setmode HAVE_SETMODE)
check_function_exists(strdup HAVE_STRDUP)
check_function_exists(strerror_s HAVE_STRERROR_S)
check_function_exists(strerrorlen_s HAVE_STRERRORLEN_S)
check_function_exists(stricmp HAVE_STRICMP)
check_function_exists(strncpy_s HAVE_STRNCPY_S)
check_function_exists(strtoll HAVE_STRTOLL)
check_function_exists(strtoull HAVE_STRTOULL)
check_function_exists(strncasecmp HAVE_STRNCASECMP)


check_symbol_exists(_snprintf stdio.h HAVE__SNPRINTF)
check_symbol_exists(_snprintf_s stdio.h HAVE__SNPRINTF_S)
check_symbol_exists(_snwprintf_s stdio.h HAVE__SNWPRINTF_S)
check_symbol_exists(_stricmp string.h HAVE__STRICMP)
check_symbol_exists(localtime_r time.h HAVE_LOCALTIME_R)
check_symbol_exists(localtime_s time.h HAVE_LOCALTIME_S)
check_symbol_exists(snprintf stdio.h HAVE_SNPRINTF)
check_symbol_exists(snprintf_s stdio.h HAVE_SNPRINTF_S)
check_symbol_exists(strcasecmp strings.h HAVE_STRCASECMP)
check_symbol_exists(localtime_r time.h HAVE_LOCALTIME_R)
check_symbol_exists(localtime_s time.h HAVE_LOCALTIME_S)
check_symbol_exists(snprintf_s stdio.h HAVE_SNPRINTF_S)
check_symbol_exists(strcasecmp strings.h HAVE_STRCASECMP)
check_symbol_exists(_doprnt "stdio.h" HAVE_DOPRNT)
check_symbol_exists(vasprintf "stdio.h" HAVE_VASPRINTF)
check_symbol_exists(vsnprintf "stdio.h" HAVE_VSNPRINTF)
check_symbol_exists(vprintf "stdio.h" HAVE_VPRINTF)
check_symbol_exists(getentropy "sys/random.h" HAVE_DECL_GETENTROPY)
check_symbol_exists(glob "glob.h" HAVE_DECL_GLOB)
check_symbol_exists(mmap "sys/mman.h" HAVE_DECL_MMAP)

if((MSVC AND NOT(MSVC_VERSION LESS 1800)))
  check_symbol_exists(INFINITY "math.h" HAVE_DECL_INFINITY)
  check_symbol_exists(isinf "math.h" HAVE_DECL_ISINF)
  check_symbol_exists(isnan "math.h" HAVE_DECL_ISNAN)
  check_symbol_exists(nan "math.h" HAVE_DECL_NAN)
endif()

check_type_size("char" SLXIO_ABI_SIZEOF_CHAR)
check_type_size(int SLXIO_ABI_SIZEOF_INT)
check_type_size("long" SLXIO_ABI_SIZEOF_LONG)
check_type_size("short" SLXIO_ABI_SIZEOF_SHORT)
check_type_size("long long" SLXIO_ABI_SIZEOF_LONG_LONG)
check_type_size("size_t" SLXIO_ABI_SIZEOF_SIZE_T)
check_type_size("double" SLXIO_ABI_SIZEOF_DOUBLE)
check_type_size("float" SLXIO_ABI_SIZEOF_FLOAT)
check_type_size(uint8_t SLXIO_ABI_SIZEOF_UINT8_T)
check_type_size(uint16_t SLXIO_ABI_SIZEOF_UINT16_T)
check_type_size(uint32_t SLXIO_ABI_SIZEOF_UINT32_T)

check_type_size(__int8 __INT8_LIBZIP)
check_type_size(int8_t INT8_T_LIBZIP)
check_type_size(uint8_t UINT8_T_LIBZIP)
check_type_size(__int16 __INT16_LIBZIP)
check_type_size(int16_t INT16_T_LIBZIP)
check_type_size(uint16_t UINT16_T_LIBZIP)
check_type_size(__int32 __INT32_LIBZIP)
check_type_size(int32_t INT32_T_LIBZIP)
check_type_size(uint32_t UINT32_T_LIBZIP)
check_type_size(__int64 __INT64_LIBZIP)
check_type_size(int64_t INT64_T_LIBZIP)
check_type_size(uint64_t UINT64_T_LIBZIP)
check_type_size("short" SHORT_LIBZIP)
check_type_size("int" INT_LIBZIP)
check_type_size("long" LONG_LIBZIP)
check_type_size("long long" LONG_LONG_LIBZIP)
check_type_size("off_t" SIZEOF_OFF_T)
check_type_size("size_t" SIZEOF_SIZE_T)
check_type_size(int  SIZEOF_INT)
check_type_size(int64_t SIZEOF_INT64_T)
check_type_size(long SIZEOF_LONG)
check_type_size("long long" SIZEOF_LONG_LONG)
check_type_size("size_t" SIZEOF_SIZE_T)

if(MSVC)
  list(APPEND CMAKE_EXTRA_INCLUDE_FILES BaseTsd.h)
  check_type_size("SSIZE_T" SIZEOF_SSIZE_T)
else()
  check_type_size("ssize_t" SIZEOF_SSIZE_T)
endif()

check_c_source_compiles(
  "include <sys/ioctl.h>
  include <linux/fs.h>
  int main(int argc, char *argv[]) 
  { unsigned long x = FICLONERANGE; }"
  HAVE_FICLONERANGE)

check_c_source_compiles("
  void __attribute__((destructor))
  f(void) {}
  int main(void) { return 0; }
" HAVE_FUNC_ATTRIBUTE_DESTRUCTOR)

if(HAVE_INT8_T_LIBZIP)
  set(ZIP_INT8_T int8_t)
elseif(HAVE___INT8_LIBZIP)
  set(ZIP_INT8_T __int8)
else()
  set(ZIP_INT8_T "signed char")
endif()

if(HAVE_UINT8_T_LIBZIP)
  set(ZIP_UINT8_T uint8_t)
elseif(HAVE___INT8_LIBZIP)
  set(ZIP_UINT8_T "unsigned __int8")
else()
  set(ZIP_UINT8_T "unsigned char")
endif()

if(HAVE_INT16_T_LIBZIP)
  set(ZIP_INT16_T int16_t)
elseif(HAVE___INT16_LIBZIP)
  set(INT16_T_LIBZIP __int16)
elseif(SHORT_LIBZIP EQUAL 2)
  set(INT16_T_LIBZIP short)
endif()

if(HAVE_UINT16_T_LIBZIP)
  set(ZIP_UINT16_T uint16_t)
elseif(HAVE___INT16_LIBZIP)
  set(UINT16_T_LIBZIP "unsigned __int16")
elseif(SHORT_LIBZIP EQUAL 2)
  set(UINT16_T_LIBZIP "unsigned short")
endif()

if(HAVE_INT32_T_LIBZIP)
  set(ZIP_INT32_T int32_t)
elseif(HAVE___INT32_LIBZIP)
  set(ZIP_INT32_T __int32)
elseif(INT_LIBZIP EQUAL 4)
  set(ZIP_INT32_T int)
elseif(LONG_LIBZIP EQUAL 4)
  set(ZIP_INT32_T long)
endif()

if(HAVE_UINT32_T_LIBZIP)
  set(ZIP_UINT32_T uint32_t)
elseif(HAVE___INT32_LIBZIP)
  set(ZIP_UINT32_T "unsigned __int32")
elseif(INT_LIBZIP EQUAL 4)
  set(ZIP_UINT32_T "unsigned int")
elseif(LONG_LIBZIP EQUAL 4)
  set(ZIP_UINT32_T "unsigned long")
endif()

set(ZIP_INT64_T int64_t)
set(ZIP_INT64_T int64_t)
set(ZIP_INT64_T __int64)
set(ZIP_INT64_T long)
set(ZIP_INT64_T "long long")

set(ZIP_UINT64_T uint64_t)
set(ZIP_UINT64_T "unsigned __int64")
set(ZIP_UINT64_T "unsigned long")
set(ZIP_UINT64_T "unsigned long long")

if(HAVE_INTTYPES_H)
  set(
    LIBZIP_TYPES_INCLUDE
    "#if !defined(__STDC_FORMAT_MACROS)
#define __STDC_FORMAT_MACROS 1
#endif
#include <inttypes.h>")
elseif(HAVE_STDINT_H)
  set(LIBZIP_TYPES_INCLUDE "include <stdint.h>")
elseif(HAVE_SYS_TYPES_H)
  set(LIBZIP_TYPES_INCLUDE "include <sys/types.h>")
endif()

# Check to see if we have large file support
set(CMAKE_REQUIRED_DEFINITIONS -D_LARGEFILE64_SOURCE=1)
check_type_size(off64_t OFF64_T)
unset(CMAKE_REQUIRED_DEFINITIONS)  