include (CTest)

if (ENABLE_TESTING)
  enable_testing ()
  find_modules (_module_dirs ${CMAKE_CURRENT_SOURCE_DIR})
  foreach (_module_dir IN LISTS _module_dirs)
    scan_module_file (_module "${_module_dir}/Module.txt")
    if (${_module_enable_test} STREQUAL "FALSE")
      continue ()
    endif ()
    set (_module_test_dir "${_module_dir}/Testing/Cxx")
    if (IS_DIRECTORY "${_module_test_dir}")
      add_subdirectory (${_module_test_dir})
    endif ()
  endforeach ()
endif ()
