# read version string from the VERSION.txt file and 
# set the version variables.
file(READ "VERSION.txt" VERSION)
string(STRIP ${VERSION} VERSION)
if(${VERSION} MATCHES [[([0-9]+)\.([0-9]+)\.([0-9]+)]])
    set(SLXIO_MAJOR_VERSION ${CMAKE_MATCH_1})
    set(SLXIO_MINOR_VERSION ${CMAKE_MATCH_2})
    set(SLXIO_MICRO_VERSION ${CMAKE_MATCH_3})
endif()

set(PROJECT_VERSION_MAJOR ${SLXIO_MAJOR_VERSION})
set(PROJECT_VERSION_MINOR ${SLXIO_MINOR_VERSION})
set(PROJECT_VERSION_PATCH ${SLXIO_MICRO_VERSION})
set(PROJECT_VERSION 
${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})