#include "Doctest.h"
#include "slxErrorBuffer.h"

SLXIO_NAMESPACE_BEGIN
SLXIO_ABI_NAMESPACE_BEGIN

TEST_CASE("Simple Test") {

  CHECK(1 != 0);
  CHECK(2 != 3);
};

SLXIO_ABI_NAMESPACE_END
SLXIO_NAMESPACE_END