#!/usr/bin/perl -w
# SPDX-FileCopyrightText: 2025-2026 Wissem Chiha
# SPDX-License-Identifier: Apache-2.0
use strict;
use warnings;
use File::Find;

sub help()
{
    print <<END;

Command line options are:

END
	exit 0;
}

# Arguments: project_name, source_dir, build_dir
my ($project_name, $source_dir, $build_dir) = @ARGV;
die "Usage: $0 <project_name> <source_dir> <build_dir>\n"
    unless defined $build_dir;

my $single_include = "$build_dir/$project_name.h";

open my $out, ">", $single_include or die "Cannot write $single_include: $!";

print $out "// ====================================================================== \n";
print $out "// == DO NOT MODIFY THIS FILE BY HAND - IT IS AUTO GENERATED BY PERL! == \n";
print $out "// ====================================================================== \n\n";


my $license_file = "$source_dir/LICENSE-Apache-2.0";
if (-e $license_file) {
    open my $lic, "<", $license_file or die "Cannot read $license_file: $!";
    my $license = do { local $/; <$lic> };
    close $lic;
    print $out "/*\n$license\n*/\n";
}

print $out "#ifndef __slxio_h__ \n#define __slxio_h__\n\n";

my @headers;
find(
    sub {
        return unless /\.h$/;
        my $path = $File::Find::name;

        return if $path =~ /ThirdParty/;
        return if $path =~ /Documentation/;
        return if $path =~ /Testing/;
        return if $path =~ /Examples/;
        return if $path =~ /build/;
        return if $path =~ /cmake/;
        push @headers, $path;
    },
    $source_dir
);

for my $hdr (@headers) {
    print $out "#include \"$hdr\"\n";
}

print $out "\n#endif /* __slxio_h__ */ \n";

close $out;
