#!/usr/bin/env python3 
# SPDX-FileCopyrightText: 2025-2026 Wissem Chiha
# SPDX-License-Identifier: Apache-2.0
#
# enumeration editor tool 
# this tool  is develloped in order to help me mangaing large 
# project enumetaions defintion across modules and parts of the sowfatere in a clean 
# configurable way, build around slxio.enum file
# the idea was somhwo inspired from Chronioum historgram enumartion xml 
# and the autosar worflows 


# hwo to use :
# MergeEnumMap --enum-map-file 'path/to/enum.map' -root-dir 'path/to/slxio/root' -ouput-file 'path/to/ouput/header.h'
# by default it will update and gnerte the slxio.enium file in the root dir with the merged enumeration definitions
# parse all slxio.enum files for all modules, for each enum value compute a unique identifer 
# within the project 

import os

# parse the enum map file to get the mapping between module id and module name, 
# and group id and group name
def parse_enum_map_file(filename):

    names = {}
    groups = {}
    current_section = None

    with open(filename, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith("NAME"):
                current_section = "NAME"
                continue
            elif line.startswith("GROUP"):
                current_section = "GROUP"
                continue
            parts = line.split(None, 1)
            if len(parts) == 2:
                module_id, module_name = parts
                entry = {"id": int(module_id), "name": module_name}
                if current_section == "NAME":
                    names[module_name] = int(module_id)
                elif current_section == "GROUP":
                    groups[module_name] = int(module_id)

    return names, groups

# read metada fro mslxio.module to get name and groupe name 
def parse_module_file(filename):
    print(f"Parsing module file: {filename}")
    module_name = None
    group_name = None
    current_section = None

    with open(filename, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.upper() == "NAME":
                current_section = "NAME"
                continue
            elif line.upper() == "GROUP":
                current_section = "GROUP"
                continue
            if current_section == "NAME":
                module_name = line
                current_section = None
            elif current_section == "GROUP":
                group_name = line
                current_section = None

    return module_name, group_name

# read a given enumeration file 
# return tuple
def parse_enum_file(path):
    enums = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split(None, 1)  
            if len(parts) == 2:
                code, ident = parts
                enums.append((int(code), ident))  
    return enums


# this function will generate the final enumeration definitions 
# by merging the enums with the names and groups 
# and return a list of enumeration definitions 
def merge_enum_definitions(enums, names, groups):
    enum_definitions = []
    
    names_rev = {v: k for k, v in names.items()}
    groups_rev = {v: k for k, v in groups.items()}

    for code, ident in enums:
        group_id = (code >> 28) & 0xF
        module_id = (code >> 16) & 0xFF
        error_id = code & 0xFFFF

        module_name = names_rev.get(module_id)
        group_name = groups_rev.get(group_id)

        if module_name and group_name:
            enum_definitions.append({
                "code": code,
                "ident": ident,
                "module": module_name,
                "group": group_name,
                "error": error_id
            })

    return enum_definitions

# by default all error code are 32 bist signed integres, 
# 8 most sig bist for Group id 
# 8 bits for module id 
# 16 bits for error code
def get_enum_global_id(group_id, module_id, error_code):
    error_val = abs(error_code) & 0xFFFF
    return (group_id << 24) | (module_id << 16) | error_val


# by default it genrate a C99 header file 
def generate_enum_header(enum_definitions, output_file):
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("// SPDX-FileCopyrightText: 2025-2026 Wissem Chiha\n")
        f.write("// SPDX-License-Identifier: Apache-2.0\n")

        f.write("\n//===============================================================\n")
        f.write(f"// AUTOGENERATED BY {os.path.basename(__file__)} SCRIPT — DO NOT EDIT BY HAND!\n")
        f.write("//===============================================================\n")
        f.write("\n")

        f.write("#ifndef __ErrorTypes_h__\n")
        f.write("#define __ErrorTypes_h__\n\n")

        for ident, gid in enum_definitions.items():
            f.write("\n")
            f.write(f"#ifdef {ident}\n")
            f.write(f"#undef {ident}\n")
            f.write(f"#endif\n")
            f.write(f"#define {ident}  0x{gid:08X}\n")

        f.write("\n")
        f.write("#endif /* __ErrorTypes_h__*/ \n")


def main(root_dir, mapping_file, output_header):
    names, groups = parse_enum_map_file(mapping_file)
    merged = {}

    for dirpath, dirnames, filenames in os.walk(root_dir):
        module_file = os.path.join(dirpath, "slxio.module")
        enum_file = os.path.join(dirpath, "slxio.enum")

        if not os.path.exists(module_file) or not os.path.exists(enum_file):
            continue

        module_name, group_name = parse_module_file(module_file)
        if(not module_name or not group_name):
            print(f"Warning: Missing module or group name in {module_file}, skip.")
            continue
        print(f"Processing module: {module_name}, group: {group_name}")

        module_id = names.get(module_name)
        group_id = groups.get(group_name)

        enums = parse_enum_file(enum_file)
        for code, ident in enums:
            gid = get_enum_global_id(group_id, module_id, code)
            merged[ident] = gid

    generate_enum_header(merged, output_header)


if __name__ == "__main__":
    main("C:/Users/chiha.000/Documents/github/slxio",
        "C:/Users/chiha.000/Documents/github/slxio/Utilities/Scripts/enum.map",
        "C:/Users/chiha.000/Documents/github/slxio/Common/Core/ErrorTypes.h")

