name: MacOS
on: [push, pull_request]
jobs:
  cmake:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 80
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: MacOS AppleClang Default
            os: macos-latest
            compiler: clang
            cxx-compiler: clang++
            cmake-args:

          - name: MacOS AppleClang C++14
            os: macos-latest
            compiler: clang
            cxx-compiler: clang++
            cmake-args: -DCMAKE_CXX_STANDARD=14

          - name: MacOS GNU GCC Homebrew C++14
            os: macos-latest
            compiler: gcc-13
            cxx-compiler: g++-13
            cmake-args: -DCMAKE_CXX_STANDARD=14
            packages: gcc@13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packages
        if: ${{ matrix.packages }}
        run: brew install ${{ matrix.packages }}

      - name: Configure
        run: cmake -S . -B build ${{ matrix.cmake-args }}
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.cxx-compiler }}

      - name: Build
        run: cmake --build build

      - name: Upload Build Folder
        uses: actions/upload-artifact@v4
        with:
            name: build-${{ matrix.name }}
            path: build/

      - name: Test
        run: ctest --output-on-failure --max-width 150
        working-directory: build
