name: MinGW

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install MinGW manually
        run: |
          choco install mingw --yes
          echo "C:\\ProgramData\\chocolatey\\bin" >> $env:GITHUB_PATH
          echo "C:\\ProgramData\\chocolatey\\lib\\mingw\\tools\\install\\mingw64\\bin" >> $env:GITHUB_PATH

      - name: Configure CMake
        run: cmake -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        run: ctest --test-dir build --output-on-failure
        continue-on-error: true
