name: MinGW

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install MinGW
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-ctest

    - name: Add MinGW to PATH
      run: echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
    
    - name: Check GCC version
      run: gcc --version

    - name: Configure CMake
      run: cmake -B build -S ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build with MinGW
      run: cmake --build build

    - name: Test
      run: ctest --output-on-failure
      working-directory: build
