name: Ubuntu
on: [push, pull_request]
jobs:
  cmake:
    name: ${{matrix.name}}
    runs-on: ${{matrix.os}}
    timeout-minutes: 80
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu GNU GCC Default
            os: ubuntu-latest
            compiler: gcc
            cflags: -Wall -Wextra
            pkgtgt: package package_source
            cmake-args:

          - name: Ubuntu GNU GCC C++14
            os: ubuntu-latest
            compiler: gcc
            cxx-compiler: g++
            cmake-args: -DCMAKE_CXX_STANDARD=14

          - name: Ubuntu Clang C++14
            os: ubuntu-latest
            compiler: clang-15
            cxx-compiler: clang++-15
            cmake-args: -DCMAKE_CXX_STANDARD=14
            packages: clang-15 llvm-15 llvm-15-tools

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install packages
      if: ${{matrix.packages}}
      run: sudo apt-get update && sudo apt-get install -y ${{ join(matrix.packages, ' ') }}

    - name: Configure
      run: cmake -S . -B build ${{ matrix.cmake-args }}
      env:
          CC: ${{matrix.compiler}}
          CXX: ${{matrix.cxx-compiler}}
          CFLAGS: ${{matrix.cflags}}

    - name: Build
      run: cmake --build build
    
    - name: Upload Build Folder
      uses: actions/upload-artifact@v4
      with:
          name: build-${{ matrix.name }}
          path: build/

    - name: Test
      run: ctest --output-on-failure --max-width 150
      working-directory: build
