name: Windows

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  cmake:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        compiler: 
          - msvc
          - clang
        configuration: 
          - Debug
          - Release
        platform: 
          - Win32
          - x64
        python-version: 
          - 3.12
        os: 
          - windows-latest

        include:
          - compiler: msvc
            platform: Win32
            name: Windows MSVC Win32 ${{ matrix.configuration }}
            cmake-args: -A Win32 -G "Visual Studio 17 2022" -DCMAKE_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
            python-arch: x86

          - compiler: msvc
            platform: x64
            name: Windows MSVC x64 ${{ matrix.configuration }}
            cmake-args: -A x64 -G "Visual Studio 17 2022" -DCMAKE_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
            python-arch: x64

          - compiler: clang
            platform: Win32
            name: Windows Clang Win32 ${{ matrix.configuration }}
            cmake-args: -G Ninja -DCMAKE_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
            python-arch: x86
            cxx-compiler: clang++

          - compiler: clang
            platform: x64
            name: Windows Clang x64 ${{ matrix.configuration }}
            cmake-args: -G Ninja -DCMAKE_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
            python-arch: x64
            cxx-compiler: clang++

    steps:
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
            architecture: ${{ matrix.python-arch }}

        - name: Install MSVC Build Tools
          if: ${{ matrix.compiler == 'msvc' }}
          run: choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional --passive --locale en-US"

        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Configure
          run: >
            cmake -S . -B build
            ${{ matrix.cmake-args }}
            -DPython_EXECUTABLE=${{ env.pythonLocation }}/python.exe
          env:
            CC: ${{ matrix.compiler }}
            CXX: ${{ matrix.cxx-compiler }}

        - name: Build
          run: cmake --build build

        - name: Test
          run: ctest -C ${{ matrix.configuration }} --output-on-failure --max-width 150
          working-directory: build