name: Windows

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -S ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}


    - name: Build with MSVC
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
      working-directory: build
